-- MySQL Script generated by MySQL Workbench
-- Mon May 29 20:27:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `valid` TINYINT NOT NULL DEFAULT 0,
  `since` DATETIME NOT NULL,
  `pass` CHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `since` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group_has_user` (
  `group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `user_id`),
  INDEX `fk_group_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_group_has_user_group_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_user_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_since` DATETIME NOT NULL,
  `date_end_of_voting` DATETIME NOT NULL,
  `date_appointed` DATETIME NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `group_id`),
  INDEX `fk_date_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_date_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_voting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_voting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imdb_id` INT NOT NULL,
  `points` INT NOT NULL DEFAULT 0,
  `date_id` INT NOT NULL,
  `date_group_id` INT NOT NULL,
  PRIMARY KEY (`id`, `date_id`, `date_group_id`),
  INDEX `fk_movie_voting_date1_idx` (`date_id` ASC, `date_group_id` ASC),
  CONSTRAINT `fk_movie_voting_date1`
    FOREIGN KEY (`date_id` , `date_group_id`)
    REFERENCES `mydb`.`date` (`id` , `group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'movelect' IDENTIFIED BY 'K;G8;nSCKz\fljZV';

GRANT ALL ON `mydb`.* TO 'movelect';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
